In [1]:
import numpy as np

In [2]:
A = np.array([[1, -4, 9],
              [3, 5, 11],
              [4, 7, -5]])

In [3]:
B = np.array([[0, 0, -1],
              [-1, 5, 0],
              [9, -7, 0]])

In [4]:
A @ B

array([[ 85, -83,  -1],
       [ 94, -52,  -3],
       [-52,  70,  -4]])

In [5]:
B1 = np.array([[2, 0, 0],
               [0, 5, 0],
               [0, 0, 7]])

In [6]:
A @ B1

array([[  2, -20,  63],
       [  6,  25,  77],
       [  8,  35, -35]])

In [7]:
B2 = np.array([[2, -1, 5],
               [0, 5, 2],
               [0, 0, 7]])

In [8]:
A @ B2

array([[  2, -21,  60],
       [  6,  22, 102],
       [  8,  31,  -1]])

## Order of matrix multiplication (commutativity)

In [9]:
A = np.array([[3, 6],
              [7, 8]])
B = np.array([[6, -7],
              [1, 2]])

In [10]:
A @ B

array([[ 24,  -9],
       [ 50, -33]])

In [11]:
B @ A

array([[-31, -20],
       [ 17,  22]])