## First-class functions
The concept of first-class functions in Python allows functions to be treated as first-class objects. This means that functions can be passed as arguments to other functions, returned from other functions, and assigned to variables. This is a fundamental concept in functional programming, which is a programming paradigm that treats computation as the evaluation of mathematical functions and avoids changing-state and mutable data.

In [1]:
# Assign function to a variable
def greet(name):
    return f"Hello, {name}!"


Assign function to a variable

In [2]:
say_hello = greet  # Assign function to a variable
print(say_hello("Alice"))

Hello, Alice!


### Higher-order functions
Higher-order functions are functions that take other functions as arguments or return functions as results. They enable a functional programming style and are a key feature of many programming languages, including Python.

In [3]:
# Higher-order function: Takes a function as an argument
def apply_func(func, value):
    return func(value)


In [4]:
# Define a simple function
def square(x):
    return x ** 2

In [5]:
# Apply the function using the higher-order function
result = apply_func(square, 5)
print(result)

25


Example of returning a function from another function

In [6]:
def multiplier(factor):
    def multiply(x):
        return x * factor
    return multiply

In [7]:
double = multiplier(2)  # Creates a function that multiplies by 2
print(double(4))

8


### Lambda functions
Lambda functions, also known as anonymous functions, are a way of defining small, unnamed functions in Python. They are defined using the `lambda` keyword and are often used as arguments to higher-order functions.

In [8]:
add = lambda x, y: x + y
print(add(3, 5))  # Output: 8

8


Example of using lambda functions with higher-order functions, such as conditionals

In [9]:
max_value = lambda x, y: x if x > y else y
print(max_value(10, 20))  # Output: 20

20


Sorting a list of tuples based on the second element using lambda functions

In [10]:
words = ["apple", "banana", "cherry"]
words.sort(key=lambda x: len(x))  # Sort by word length
print(words)  # Output: ['apple', 'cherry', 'banana']

['apple', 'banana', 'cherry']


### Map, Filter, and Reduce
Map, filter, and reduce are common functional programming operations that can be used with lambda functions to process data more efficiently.

In [11]:
def square(x):
    return x ** 2

nums = [1, 2, 3, 4]
squared = list(map(square, nums))
print(squared)  # Output: [1, 4, 9, 16]

[1, 4, 9, 16]


In [12]:
# Using lambda functions with map
nums = [1, 2, 3, 4]
squared = list(map(lambda x: x ** 2, nums))
print(squared)  # Output: [1, 4, 9, 16]

[1, 4, 9, 16]


Filter example using lambda functions

In [14]:
def is_even(x):
    return x % 2 == 0

nums = [1, 2, 3, 4, 5, 6]
evens = list(filter(is_even, nums))
print(evens)  # Output: [2, 4, 6]


[2, 4, 6]


In [16]:
# With lambda functions
nums = [1, 2, 3, 4, 5, 6]
evens = list(filter(lambda x: x % 2 == 0, nums))
print(evens)  # Output: [2, 4, 6]

[2, 4, 6]


Reduce example using lambda functions

In [17]:
from functools import reduce

def multiply(x, y):
    return x * y

nums = [1, 2, 3, 4]
product = reduce(multiply, nums)
print(product)  # Output: 24


24


In [18]:
# With lambda functions
nums = [1, 2, 3, 4]
product = reduce(lambda x, y: x * y, nums)
print(product)  # Output: 24

24


# Functools module
The `functools` module in Python provides higher-order functions that can be used for various purposes, such as caching, partial function application, and more.

In [19]:
from functools import reduce
nums = [1, 2, 3, 4]
product = reduce(lambda x, y: x * y, nums)
print(product)  # Output: 24

24


LRU-cache example using functools

In [20]:
from functools import lru_cache

@lru_cache(maxsize=None)
def fibonacci(n):
    if n < 2:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(10))  # Output: 55


55


Partial function application example using functools

In [21]:
from functools import partial

def power(base, exponent):
    return base ** exponent

square = partial(power, exponent=2)
print(square(4))  # Output: 16


16


In [23]:
cube = partial(power, exponent=3)
print(cube(3))  # Output: 27

27


In [24]:
from functools import wraps

def decorator(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("Function is called")
        return func(*args, **kwargs)
    return wrapper

In [26]:
@decorator
def say_hello():
    '''This function prints Hello!'''
    print("Hello!")

print(say_hello.__doc__)  # Preserves function metadata

This function prints Hello!


**Key Benefits of `functools`:**
- Reduces redundant computations (`lru_cache`).
- Enables function customization (`partial`).
- Simplifies recursive and higher-order function handling.

## Functional Programming in NumPy
While NumPy is primarily used for numerical computing and array operations, it also supports functional programming paradigms through the use of vectorized operations, broadcasting, and aggregation functions.

In [27]:
import numpy as np

In [28]:
def add_ten(x):
    return x + 10

vec_add_ten = np.vectorize(add_ten)
arr = np.array([1, 2, 3])
print(vec_add_ten(arr))  # Output: [11 12 13]


[11 12 13]


Using numpy vectorize with broadcasting

In [29]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.add(x, y)  # Equivalent to x + y
# Vectorized operation using numpy and broadcasting

array([5, 7, 9])

In [30]:
x = np.array([1, 2, 3])
y = 10
np.add(x, y)  # Equivalent to x + y

array([11, 12, 13])

Using numpy apply along axis

In [31]:
def custom_func(x):
    return np.sum(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.apply_along_axis(custom_func, axis=1, arr=arr)
print(result)  # Output: [ 6 15]


[ 6 15]


## Recursion and iteration
Recursion and iteration are two fundamental concepts in programming. Recursion is a technique where a function calls itself to solve smaller instances of the same problem, while iteration involves repeatedly executing a set of statements using loops. Both techniques have their advantages and use cases, depending on the problem being solved.

In [32]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n-1)

print(factorial(5))  # Output: 120


120


In [33]:
def factorial_iter(n):
    result = 1
    for i in range(1, n+1):
        result *= i
    return result
print(factorial_iter(5))  # Output: 120

120


## Lazy evaluation with itertools
Lazy evaluation is an evaluation strategy that delays the evaluation of an expression until its value is actually needed. This can help improve performance and memory usage by avoiding unnecessary computations. The `itertools` module in Python provides functions for creating iterators for efficient lazy evaluation.

In [34]:
from itertools import count

counter = count(10, 2)  # Start from 10, step by 2
print(next(counter))  # Output: 10
print(next(counter))  # Output: 12


10
12


In [36]:
from itertools import cycle

colors = cycle(["red", "blue", "green"])
print(next(colors))  # Output: red
print(next(colors))  # Output: blue
print(next(colors))  # Output: green
print(next(colors))  # Output: red (repeats)


red
blue
green
red


In [37]:
from itertools import repeat

for val in repeat("Hello", 3):
    print(val)  # Output: Hello (3 times)

Hello
Hello
Hello


In [38]:
from itertools import islice, count

nums = islice(count(1, 1), 5)  # Take first 5 numbers
print(list(nums))  # Output: [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


In [39]:
from itertools import combinations

items = ['A', 'B', 'C']
print(list(combinations(items, 2)))


[('A', 'B'), ('A', 'C'), ('B', 'C')]


In [40]:
# Output: [('A', 'B'), ('A', 'C'), ('B', 'C')]
#### Using `groupby()`
from itertools import groupby

data = [('A', 1), ('A', 2), ('B', 3), ('B', 4)]
grouped = groupby(data, key=lambda x: x[0])

for key, group in grouped:
    print(key, list(group))
# Output: A [('A', 1), ('A', 2)]
#         B [('B', 3), ('B', 4)]


A [('A', 1), ('A', 2)]
B [('B', 3), ('B', 4)]


## Functional data processing
Functional programming concepts can be applied to data processing tasks, such as filtering, mapping, and reducing data. These concepts can help simplify code, improve readability, and enable efficient processing of large datasets.

In basic Python map, filter, and reduce are used to process data

In [35]:
nums = [1, 2, 3, 4, 5]
doubled_evens = list(
    map(lambda x: x * 2,
        filter(
            lambda x: x % 2 == 0, nums)
        )
)
print(doubled_evens)  # Output: [4, 8]

[4, 8]


In NumPy, vectorized operations can be used for efficient data processing, and also list comprehension can be used for more complex operations.

In [41]:
nums = [1, 2, 3, 4, 5, 6]
squared_evens = [x ** 2
                 for x in nums if x % 2 == 0]
print(squared_evens)  # Output: [4, 16, 36]


[4, 16, 36]


## Immutable data
Immutable data structures are those whose values cannot be changed after they are created. In Python, strings, tuples, and frozensets are examples of immutable data types. Immutable data structures are useful for ensuring data integrity and preventing unintended modifications.

In [42]:
my_tuple = (1, 2, 3)
my_tuple[0] = 10  # ❌ TypeError: 'tuple' object does not support item assignment


TypeError: 'tuple' object does not support item assignment

Frozen sets are also immutable

In [44]:
my_set = frozenset([1, 2, 3])
my_set.add(4)  # ❌ AttributeError: 'frozenset' object has no attribute 'add'


AttributeError: 'frozenset' object has no attribute 'add'

### Working with immutable data
Immutable data structures can be useful in scenarios where data integrity is important, such as when passing data between functions or modules without the risk of modification.

In [45]:
nums = [1, 2, 3, 4]
squared = list(map(lambda x: x ** 2, nums))
print(squared)  # Output: [1, 4, 9, 16]


[1, 4, 9, 16]


Creating new dictionaries instead of modifying existing ones

In [47]:
my_dict = {'a': 1, 'b': 2}
new_dict = {**my_dict, 'b': 3}  # Creates a new dictionary instead of modifying
print(new_dict)  # Output: {'a': 1, 'b': 3}


{'a': 1, 'b': 3}
